# Generated by Django 4.0.5 on 2022-07-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0003_dadostm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostm',
            name='linha',
            field=models.IntegerField(),
        ),
    ]
