# Generated by Django 4.0.5 on 2022-07-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0004_alter_dadostm_linha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_teste_mesa', models.DateField()),
            ],
        ),
    ]
