# Generated by Django 4.0.5 on 2022-07-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0006_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insert', models.DateTimeField(auto_now_add=True)),
                ('fk_programa_o', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regex.programao')),
                ('fk_programa_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regex.programap')),
            ],
        ),
        migrations.CreateModel(
            name='TesteDeMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste', models.DateTimeField(auto_now_add=True)),
                ('fk_caso_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regex.casoteste')),
            ],
        ),
        migrations.DeleteModel(
            name='TesteMesa',
        ),
    ]
