# Generated by Django 4.0.5 on 2022-07-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0007_casoteste_testedemesa_delete_testemesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('linha', models.CharField(max_length=1000)),
                ('variavel_p', models.CharField(max_length=100)),
                ('dado_hexa_p', models.CharField(max_length=100)),
                ('fk_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regex.testedemesa')),
            ],
        ),
        migrations.DeleteModel(
            name='DadosTm',
        ),
    ]
