# Generated by Django 4.0.5 on 2022-07-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0009_dicionarioparametros_valorparametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programao',
            name='dt_codificacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programap',
            name='dt_codificacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
