# Generated by Django 4.0.5 on 2022-07-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0010_alter_programao_dt_codificacao_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programas',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
        migrations.RenameField(
            model_name='casoteste',
            old_name='data_insert',
            new_name='data_caso_teste',
        ),
        migrations.RenameField(
            model_name='casoteste',
            old_name='fk_programa_o',
            new_name='programa_o',
        ),
        migrations.RenameField(
            model_name='casoteste',
            old_name='fk_programa_p',
            new_name='programa_p',
        ),
    ]
