# Generated by Django 4.0.5 on 2022-07-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0011_delete_programas_delete_teste_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosteste',
            old_name='fk_teste',
            new_name='teste',
        ),
        migrations.RenameField(
            model_name='dicionarioparametros',
            old_name='fk_teste',
            new_name='teste',
        ),
        migrations.RenameField(
            model_name='testedemesa',
            old_name='fk_caso_teste',
            new_name='caso_teste',
        ),
    ]
