# Generated by Django 4.0.5 on 2022-07-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0012_rename_fk_teste_dadosteste_teste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupamentoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.CharField(db_index=True, max_length=240)),
                ('valor', models.CharField(db_index=True, max_length=240, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='DicionarioParametros',
            new_name='Agrupamento',
        ),
        migrations.DeleteModel(
            name='ValorParametro',
        ),
        migrations.AddField(
            model_name='agrupamentoindex',
            name='agrupamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regex.agrupamento'),
        ),
    ]
