# Generated by Django 4.0.5 on 2022-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0013_agrupamentoindex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupamentoindex',
            name='entrada',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='agrupamentoindex',
            name='valor',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dadosteste',
            name='dado_hexa_p',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dadosteste',
            name='variavel_p',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='seu_codigo',
            field=models.CharField(max_length=1000),
        ),
    ]
