# Generated by Django 4.0.5 on 2022-06-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_remove_employee_emp_code_remove_employee_mobile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='seu_codigo',
        ),
    ]
