# Generated by Django 4.0.5 on 2022-06-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DadosTesteMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=5)),
                ('num_equacao', models.CharField(max_length=1)),
                ('variavel_o', models.CharField(max_length=100)),
                ('dado_hexa_o', models.CharField(max_length=100)),
                ('variavel_p', models.CharField(max_length=100)),
                ('dado_hexa_p', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_implementacao', models.DateField()),
                ('codigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_implementacao', models.DateField()),
                ('codigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValoresTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('fk_caso_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casoteste')),
            ],
        ),
        migrations.CreateModel(
            name='TesteMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_teste_mesa', models.DateField()),
                ('fk_caso_teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casoteste')),
                ('fk_dados_teste_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dadostestemesa')),
            ],
        ),
        migrations.AddField(
            model_name='casoteste',
            name='fk_programa_o',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programao'),
        ),
        migrations.AddField(
            model_name='casoteste',
            name='fk_programa_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programap'),
        ),
    ]
