# Generated by Django 4.0.5 on 2022-06-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casoteste',
            options={'verbose_name': 'Caso de teste', 'verbose_name_plural': 'Casos de teste'},
        ),
        migrations.AlterModelOptions(
            name='dadostestemesa',
            options={'verbose_name': 'Dado teste de mesa', 'verbose_name_plural': 'Dados testes de mesa'},
        ),
        migrations.AlterModelOptions(
            name='programao',
            options={'verbose_name': 'Programa O', 'verbose_name_plural': 'Programas O'},
        ),
        migrations.AlterModelOptions(
            name='programap',
            options={'verbose_name': 'Programa P', 'verbose_name_plural': 'Programas P'},
        ),
        migrations.AlterModelOptions(
            name='testemesa',
            options={'verbose_name': 'Teste de mesa', 'verbose_name_plural': 'Testes de mesa'},
        ),
        migrations.AlterModelOptions(
            name='valoresteste',
            options={'verbose_name': 'Valor caso de teste', 'verbose_name_plural': 'Valores casos de teste'},
        ),
        migrations.RemoveField(
            model_name='testemesa',
            name='fk_caso_teste',
        ),
        migrations.RemoveField(
            model_name='testemesa',
            name='fk_dados_teste_mesa',
        ),
        migrations.AddField(
            model_name='casoteste',
            name='fk_teste_mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.testemesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadostestemesa',
            name='fk_teste_mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.testemesa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='dado_hexa_o',
            field=models.CharField(max_length=100, verbose_name='Dado hexadecimal O'),
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='dado_hexa_p',
            field=models.CharField(max_length=100, verbose_name='Dado hexadecimal P'),
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='linha',
            field=models.CharField(max_length=5, verbose_name='Linha'),
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='num_equacao',
            field=models.CharField(max_length=1, verbose_name='Numero da equação'),
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='variavel_o',
            field=models.CharField(max_length=100, verbose_name='Variável O'),
        ),
        migrations.AlterField(
            model_name='dadostestemesa',
            name='variavel_p',
            field=models.CharField(max_length=100, verbose_name='Variável P'),
        ),
        migrations.AlterField(
            model_name='programao',
            name='codigo',
            field=models.TextField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='programao',
            name='data_implementacao',
            field=models.DateField(verbose_name='Data de implementação'),
        ),
        migrations.AlterField(
            model_name='programap',
            name='codigo',
            field=models.TextField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='programap',
            name='data_implementacao',
            field=models.DateField(verbose_name='Data de implementação'),
        ),
        migrations.AlterField(
            model_name='testemesa',
            name='data_teste_mesa',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='valoresteste',
            name='parametro',
            field=models.CharField(max_length=100, verbose_name='Parâmetro'),
        ),
        migrations.AlterField(
            model_name='valoresteste',
            name='valor',
            field=models.CharField(max_length=100, verbose_name='Valor'),
        ),
    ]
