# Generated by Django 4.0.5 on 2022-06-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_casoteste_options_alter_dadostestemesa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoteste',
            name='fk_teste_mesa',
        ),
        migrations.AddField(
            model_name='testemesa',
            name='fk_caso_teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.casoteste'),
            preserve_default=False,
        ),
    ]
