# Generated by Django 4.0.5 on 2022-06-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_casoteste_fk_teste_mesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadostestemesa',
            name='fk_teste_mesa',
        ),
        migrations.AddField(
            model_name='testemesa',
            name='fk_dados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.dadostestemesa'),
            preserve_default=False,
        ),
    ]
