# Generated by Django 4.0.5 on 2022-06-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dadostestemesa_fk_teste_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programao',
            name='data_implementacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de implementação'),
        ),
        migrations.AlterField(
            model_name='programap',
            name='data_implementacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de implementação'),
        ),
    ]
