# Generated by Django 4.0.5 on 2022-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_programao_data_implementacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraReservada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=50, verbose_name='Palavra')),
            ],
            options={
                'verbose_name': 'Palavra reservada',
                'verbose_name_plural': 'Palavras reservadas',
            },
        ),
    ]
