# Generated by Django 4.0.5 on 2022-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_palavrareservada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadostestemesa',
            name='linha',
            field=models.CharField(max_length=1000, verbose_name='Linha'),
        ),
    ]
