# Generated by Django 4.0.5 on 2022-06-28 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dadostestemesa_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoteste',
            name='add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Adicionado'),
            preserve_default=False,
        ),
    ]
