# Generated by Django 4.0.5 on 2022-07-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_testemesa_fk_dados_dadostestemesa_fk_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testemesa',
            name='data_teste_mesa',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
