# Generated by Django 4.0.5 on 2022-07-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_valorparametro_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValoresTeste',
        ),
    ]
